// 회원가입
const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

// 로그인
const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

// 로그아웃
const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

//내 정보 서버로부터 불러오기
const LOAD_MY_INFO_REQUEST = 'LOAD_MY_INFO_REQUEST';
const LOAD_MY_INFO_SUCCESS = 'LOAD_MY_INFO_SUCCESS';
const LOAD_MY_INFO_FAILURE = 'LOAD_MY_INFO_FAILURE';

// 프로필 수정
const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

// 일지 리스트 불러오기
const FETCH_NOTE_LIST_REQUEST = 'FETCH_NOTE_LIST_REQUEST';
const FETCH_NOTE_LIST_SUCCESS = 'FETCH_NOTE_LIST_SUCCESS';
const FETCH_NOTE_LIST_FAILURE = 'FETCH_NOTE_LIST_FAILURE';

// 일지 쓰기
const UPLOAD_NOTE_REQUEST = 'UPLOAD_NOTE_REQUEST';
const UPLOAD_NOTE_SUCCESS = 'UPLOAD_NOTE_SUCCESS';
const UPLOAD_NOTE_FAILURE = 'UPLOAD_NOTE_FAILURE';

// 일지 하나 불러오기
const FETCH_NOTE_REQUEST = 'FETCH_NOTE_REQUEST';
const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE';
// 일지 총 길이 불러오기
const FETCH_NOTE_LENGTH_REQUEST = 'FETCH_NOTE_LENGTH_REQUEST';
const FETCH_NOTE_LENGTH_SUCCESS = 'FETCH_NOTE_LENGTH_SUCCESS';
const FETCH_NOTE_LENGTH_FAILURE = 'FETCH_NOTE_LENGTH_FAILURE';
// 일지 수정하기
const EDIT_NOTE_REQUEST = 'EDIT_NOTE_REQUEST';
const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
const EDIT_NOTE_FAILURE = 'EDIT_NOTE_FAILURE';

// 일지 삭제하기
const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

// 일지 public 전환하기
const MAKE_NOTE_PUBLIC_REQUEST = 'MAKE_NOTE_PUBLIC_REQUEST';
const MAKE_NOTE_PUBLIC_SUCCESS = 'MAKE_NOTE_PUBLIC_SUCCESS';
const MAKE_NOTE_PUBLIC_FAILURE = 'MAKE_NOTE_PUBLIC_FAILURE';

// 일지 private 전환하기
const MAKE_NOTE_PRIVATE_REQUEST = 'MAKE_NOTE_PRIVATE_REQUEST';
const MAKE_NOTE_PRIVATE_SUCCESS = 'MAKE_NOTE_PRIVATE_SUCCESS';
const MAKE_NOTE_PRIVATE_FAILURE = 'MAKE_NOTE_PRIVATE_FAILURE';
// 일지 신고하기
const REPORT_NOTE_REQUEST = 'REPORT_NOTE_REQUEST';
const REPORT_NOTE_SUCCESS = 'REPORT_NOTE_SUCCESS';
const REPORT_NOTE_FAILURE = 'REPORT_NOTE_FAILURE';

// 메뉴 항목 선택
const SELECT_MENU_REQUEST = 'SELECT_MENU_REQUEST';

export {
	//회원가입
	REGISTER_USER_REQUEST,
	REGISTER_USER_SUCCESS,
	REGISTER_USER_FAILURE,
	// 로그인
	LOGIN_USER_REQUEST,
	LOGIN_USER_SUCCESS,
	LOGIN_USER_FAILURE,
	//로그아웃
	LOGOUT_USER_REQUEST,
	LOGOUT_USER_SUCCESS,
	LOGOUT_USER_FAILURE,
	//내 정보 서버로부터 불러오기
	LOAD_MY_INFO_REQUEST,
	LOAD_MY_INFO_SUCCESS,
	LOAD_MY_INFO_FAILURE,
	// 프로필 수정
	EDIT_PROFILE_REQUEST,
	EDIT_PROFILE_SUCCESS,
	EDIT_PROFILE_FAILURE,
	// 일지 리스트 가져오기
	FETCH_NOTE_LIST_REQUEST,
	FETCH_NOTE_LIST_SUCCESS,
	FETCH_NOTE_LIST_FAILURE,
	// 일지 쓰기
	UPLOAD_NOTE_REQUEST,
	UPLOAD_NOTE_SUCCESS,
	UPLOAD_NOTE_FAILURE,
	// 일지 하나 가져오기
	FETCH_NOTE_REQUEST,
	FETCH_NOTE_SUCCESS,
	FETCH_NOTE_FAILURE,
	// 일지 총 길이 가져오기
	FETCH_NOTE_LENGTH_REQUEST,
	FETCH_NOTE_LENGTH_SUCCESS,
	FETCH_NOTE_LENGTH_FAILURE,
	// 일지 수정하기
	EDIT_NOTE_REQUEST,
	EDIT_NOTE_SUCCESS,
	EDIT_NOTE_FAILURE,
	// 일지 삭제하기
	DELETE_NOTE_REQUEST,
	DELETE_NOTE_SUCCESS,
	DELETE_NOTE_FAILURE,
	// 일지 public 전환
	MAKE_NOTE_PUBLIC_REQUEST,
	MAKE_NOTE_PUBLIC_SUCCESS,
	MAKE_NOTE_PUBLIC_FAILURE,
	// 일지 private 전환
	MAKE_NOTE_PRIVATE_REQUEST,
	MAKE_NOTE_PRIVATE_SUCCESS,
	MAKE_NOTE_PRIVATE_FAILURE,
	// 일지 신고하기
	REPORT_NOTE_REQUEST,
	REPORT_NOTE_SUCCESS,
	REPORT_NOTE_FAILURE,
	// 메뉴에서 항목 선택
	SELECT_MENU_REQUEST,
};
