// 회원가입
const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';
// 이메일 인증
const AUTH_USER_REQUEST = 'AUTH_USER_REQUEST';
const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
const AUTH_USER_FAILURE = 'AUTH_USER_FAILURE';
// 이메일 재전송
const AUTH_AGAIN_REQUEST = 'AUTH_AGAIN_REQUEST';
const AUTH_AGAIN_SUCCESS = 'AUTH_AGAIN_SUCCESS';
const AUTH_AGAIN_FAILURE = 'AUTH_AGAIN_FAILURE';

// 대기중인 유저 가져오기
const FETCH_PENDING_USER_REQUEST = 'FETCH_PENDING_USER_REQUEST';
const FETCH_PENDING_USER_SUCCESS = 'FETCH_PENDING_USER_SUCCESS';
const FETCH_PENDING_USER_FAILURE = 'FETCH_PENDING_USER_FAILURE';

// 로그인
const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

// 로그아웃
const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

//내 정보 서버로부터 불러오기
const LOAD_MY_INFO_REQUEST = 'LOAD_MY_INFO_REQUEST';
const LOAD_MY_INFO_SUCCESS = 'LOAD_MY_INFO_SUCCESS';
const LOAD_MY_INFO_FAILURE = 'LOAD_MY_INFO_FAILURE';

// 다른 사람 정보 서버로부터 불러오기
const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST';
const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE';

// 프로필 수정
const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST';
const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

// 일지 리스트 불러오기
const FETCH_NOTE_LIST_REQUEST = 'FETCH_NOTE_LIST_REQUEST';
const FETCH_NOTE_LIST_SUCCESS = 'FETCH_NOTE_LIST_SUCCESS';
const FETCH_NOTE_LIST_FAILURE = 'FETCH_NOTE_LIST_FAILURE';

// 일지 쓰기
const UPLOAD_NOTE_REQUEST = 'UPLOAD_NOTE_REQUEST';
const UPLOAD_NOTE_SUCCESS = 'UPLOAD_NOTE_SUCCESS';
const UPLOAD_NOTE_FAILURE = 'UPLOAD_NOTE_FAILURE';

// 일지 하나 불러오기
const FETCH_NOTE_REQUEST = 'FETCH_NOTE_REQUEST';
const FETCH_NOTE_SUCCESS = 'FETCH_NOTE_SUCCESS';
const FETCH_NOTE_FAILURE = 'FETCH_NOTE_FAILURE';
// 일지 총 길이 불러오기
const FETCH_NOTE_LENGTH_REQUEST = 'FETCH_NOTE_LENGTH_REQUEST';
const FETCH_NOTE_LENGTH_SUCCESS = 'FETCH_NOTE_LENGTH_SUCCESS';
const FETCH_NOTE_LENGTH_FAILURE = 'FETCH_NOTE_LENGTH_FAILURE';
// 일지 수정하기
const EDIT_NOTE_REQUEST = 'EDIT_NOTE_REQUEST';
const EDIT_NOTE_SUCCESS = 'EDIT_NOTE_SUCCESS';
const EDIT_NOTE_FAILURE = 'EDIT_NOTE_FAILURE';

// 일지 삭제하기
const DELETE_NOTE_REQUEST = 'DELETE_NOTE_REQUEST';
const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
const DELETE_NOTE_FAILURE = 'DELETE_NOTE_FAILURE';

// 일지 public 전환하기
const MAKE_NOTE_PUBLIC_REQUEST = 'MAKE_NOTE_PUBLIC_REQUEST';
const MAKE_NOTE_PUBLIC_SUCCESS = 'MAKE_NOTE_PUBLIC_SUCCESS';
const MAKE_NOTE_PUBLIC_FAILURE = 'MAKE_NOTE_PUBLIC_FAILURE';

// 일지 private 전환하기
const MAKE_NOTE_PRIVATE_REQUEST = 'MAKE_NOTE_PRIVATE_REQUEST';
const MAKE_NOTE_PRIVATE_SUCCESS = 'MAKE_NOTE_PRIVATE_SUCCESS';
const MAKE_NOTE_PRIVATE_FAILURE = 'MAKE_NOTE_PRIVATE_FAILURE';
// 일지 신고하기
const REPORT_NOTE_REQUEST = 'REPORT_NOTE_REQUEST';
const REPORT_NOTE_SUCCESS = 'REPORT_NOTE_SUCCESS';
const REPORT_NOTE_FAILURE = 'REPORT_NOTE_FAILURE';

// 팔로우 하기
const FOLLOW_REQUEST = 'FOLLOW_REQUEST';
const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
const FOLLOW_FAILURE = 'FOLLOW_FAILURE';
// 언팔로우 하기
const UNFOLLOW_REQUEST = 'UNFOLLOW_REQUEST';
const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
const UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE';
// search user에서 팔로우
const SEARCH_FOLLOW_REQUEST = 'SEARCH_FOLLOW_REQUEST';
const SEARCH_FOLLOW_SUCCESS = 'SEARCH_FOLLOW_SUCCESS';
const SEARCH_FOLLOW_FAILURE = 'SEARCH_FOLLOW_FAILURE';
// serach user에서 언팔로우 하기
const SEARCH_UNFOLLOW_REQUEST = 'SEARCH_UNFOLLOW_REQUEST';
const SEARCH_UNFOLLOW_SUCCESS = 'SEARCH_UNFOLLOW_SUCCESS';
const SEARCH_UNFOLLOW_FAILURE = 'SEARCH_UNFOLLOW_FAILURE';
// 팔로우 리스트 부르기
const FETCH_FOLLOWINGS_REQUEST = 'FETCH_FOLLOWINGS_REQUEST';
const FETCH_FOLLOWINGS_SUCCESS = 'FETCH_FOLLOWINGS_SUCCESS';
const FETCH_FOLLOWINGS_FAILURE = 'FETCH_FOLLOWINGS_FAILURE';
//  팔로우 총 숫자 가져오기
const FETCH_FOLLOWERS_LENGTH_REQUEST = 'FETCH_FOLLOWERS_LENGTH_REQUEST';
const FETCH_FOLLOWERS_LENGTH_SUCCESS = 'FETCH_FOLLOWERS_LENGTH_SUCCESS';
const FETCH_FOLLOWERS_LENGTH_FAILURE = 'FETCH_FOLLOWERS_LENGTH_FAILURE';
// 팔로워 리스트 부르기
const FETCH_FOLLOWERS_REQUEST = 'FETCH_FOLLOWERS_REQUEST';
const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS';
const FETCH_FOLLOWERS_FAILURE = 'FETCH_FOLLOWERS_FAILURE';
// 팔로워 총 숫자 가져오기
const FETCH_FOLLOWINGS_LENGTH_REQUEST = 'FETCH_FOLLOWINGS_LENGTH_REQUEST';
const FETCH_FOLLOWINGS_LENGTH_SUCCESS = 'FETCH_FOLLOWINGS_LENGTH_SUCCESS';
const FETCH_FOLLOWINGS_LENGTH_FAILURE = 'FETCH_FOLLOWINGS_LENGTH_FAILURE';

// 유저 검색
const SEARCH_USER_REQUEST = 'SEARCH_USER_REQUEST';
const SEARCH_USER_SUCCESS = 'SEARCH_USER_SUCCESS';
const SEARCH_USER_FAILURE = 'SEARCH_USER_FAILURE';
// 유저 검색 총 숫자
const SEARCH_USER_LENGTH_REQUEST = 'SEARCH_USER_LENGTH_REQUEST';
const SEARCH_USER_LENGTH_SUCCESS = 'SEARCH_USER_LENGTH_SUCCESS';
const SEARCH_USER_LENGTH_FAILURE = 'SEARCH_USER_LENGTH_FAILURE';
// 게시글 검색
const SEARCH_POSTS_REQUEST = 'SEARCH_POSTS_REQUEST';
const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
const SEARCH_POSTS_FAILURE = 'SEARCH_POSTS_FAILURE';
// 사진 검색
const SEARCH_PHOTOS_REQUEST = 'SEARCH_PHOTOS_REQUEST';
const SEARCH_PHOTOS_SUCCESS = 'SEARCH_PHOTOS_SUCCESS';
const SEARCH_PHOTOS_FAILURE = 'SEARCH_PHOTOS_FAILURE';
// 질문글 검색
const SEARCH_QUESTIONS_REQUEST = 'SEARCH_QUESTIONS_REQUEST';
const SEARCH_QUESTIONS_SUCCESS = 'SEARCH_QUESTIONS_SUCCESS';
const SEARCH_QUESTIONS_FAILURE = 'SEARCH_QUESTIONS_FAILURE';

// 메뉴 항목 선택
const SELECT_MENU_REQUEST = 'SELECT_MENU_REQUEST';
// search navigation 선택
const SELECT_NAVIGATION_REQUEST = 'SELECT_NAVIGATION_REQUEST';

export {
	//회원가입
	REGISTER_USER_REQUEST,
	REGISTER_USER_SUCCESS,
	REGISTER_USER_FAILURE,
	// 이메일 인증
	AUTH_USER_REQUEST,
	AUTH_USER_SUCCESS,
	AUTH_USER_FAILURE,
	// 이메일 재전송
	AUTH_AGAIN_REQUEST,
	AUTH_AGAIN_SUCCESS,
	AUTH_AGAIN_FAILURE,
	// 대기 중인 유저 정보 가져오기
	FETCH_PENDING_USER_REQUEST,
	FETCH_PENDING_USER_SUCCESS,
	FETCH_PENDING_USER_FAILURE,
	// 로그인
	LOGIN_USER_REQUEST,
	LOGIN_USER_SUCCESS,
	LOGIN_USER_FAILURE,
	//로그아웃
	LOGOUT_USER_REQUEST,
	LOGOUT_USER_SUCCESS,
	LOGOUT_USER_FAILURE,
	//내 정보 서버로부터 불러오기
	LOAD_MY_INFO_REQUEST,
	LOAD_MY_INFO_SUCCESS,
	LOAD_MY_INFO_FAILURE,
	// 다른 사람 정보 서버로부터 불러오기
	FETCH_USER_INFO_REQUEST,
	FETCH_USER_INFO_SUCCESS,
	FETCH_USER_INFO_FAILURE,
	// 프로필 수정
	EDIT_PROFILE_REQUEST,
	EDIT_PROFILE_SUCCESS,
	EDIT_PROFILE_FAILURE,
	// 일지 리스트 가져오기
	FETCH_NOTE_LIST_REQUEST,
	FETCH_NOTE_LIST_SUCCESS,
	FETCH_NOTE_LIST_FAILURE,
	// 일지 쓰기
	UPLOAD_NOTE_REQUEST,
	UPLOAD_NOTE_SUCCESS,
	UPLOAD_NOTE_FAILURE,
	// 일지 하나 가져오기
	FETCH_NOTE_REQUEST,
	FETCH_NOTE_SUCCESS,
	FETCH_NOTE_FAILURE,
	// 일지 총 길이 가져오기
	FETCH_NOTE_LENGTH_REQUEST,
	FETCH_NOTE_LENGTH_SUCCESS,
	FETCH_NOTE_LENGTH_FAILURE,
	// 일지 수정하기
	EDIT_NOTE_REQUEST,
	EDIT_NOTE_SUCCESS,
	EDIT_NOTE_FAILURE,
	// 일지 삭제하기
	DELETE_NOTE_REQUEST,
	DELETE_NOTE_SUCCESS,
	DELETE_NOTE_FAILURE,
	// 일지 public 전환
	MAKE_NOTE_PUBLIC_REQUEST,
	MAKE_NOTE_PUBLIC_SUCCESS,
	MAKE_NOTE_PUBLIC_FAILURE,
	// 일지 private 전환
	MAKE_NOTE_PRIVATE_REQUEST,
	MAKE_NOTE_PRIVATE_SUCCESS,
	MAKE_NOTE_PRIVATE_FAILURE,
	// 일지 신고하기
	REPORT_NOTE_REQUEST,
	REPORT_NOTE_SUCCESS,
	REPORT_NOTE_FAILURE,
	// 팔로우 하기
	FOLLOW_REQUEST,
	FOLLOW_SUCCESS,
	FOLLOW_FAILURE,
	// 언팔로우 하기
	UNFOLLOW_REQUEST,
	UNFOLLOW_SUCCESS,
	UNFOLLOW_FAILURE,
	// search user 에서 팔로우
	SEARCH_FOLLOW_REQUEST,
	SEARCH_FOLLOW_SUCCESS,
	SEARCH_FOLLOW_FAILURE,
	// search user에서 언팔로우
	SEARCH_UNFOLLOW_REQUEST,
	SEARCH_UNFOLLOW_SUCCESS,
	SEARCH_UNFOLLOW_FAILURE,
	// 팔로워 리스트 부르기
	FETCH_FOLLOWERS_REQUEST,
	FETCH_FOLLOWERS_SUCCESS,
	FETCH_FOLLOWERS_FAILURE,
	// 팔로워 총 숫자 가져오기
	FETCH_FOLLOWERS_LENGTH_REQUEST,
	FETCH_FOLLOWERS_LENGTH_SUCCESS,
	FETCH_FOLLOWERS_LENGTH_FAILURE,
	// 팔로잉 리스트 부르기
	FETCH_FOLLOWINGS_REQUEST,
	FETCH_FOLLOWINGS_SUCCESS,
	FETCH_FOLLOWINGS_FAILURE,
	// 팔로잉 총 숫자 가져오기
	FETCH_FOLLOWINGS_LENGTH_REQUEST,
	FETCH_FOLLOWINGS_LENGTH_SUCCESS,
	FETCH_FOLLOWINGS_LENGTH_FAILURE,
	// 유저 검색
	SEARCH_USER_REQUEST,
	SEARCH_USER_SUCCESS,
	SEARCH_USER_FAILURE,
	// 유저 총 수
	SEARCH_USER_LENGTH_REQUEST,
	SEARCH_USER_LENGTH_SUCCESS,
	SEARCH_USER_LENGTH_FAILURE,
	// 게시글 검색
	SEARCH_POSTS_REQUEST,
	SEARCH_POSTS_SUCCESS,
	SEARCH_POSTS_FAILURE,
	// 사진 검색
	SEARCH_PHOTOS_REQUEST,
	SEARCH_PHOTOS_SUCCESS,
	SEARCH_PHOTOS_FAILURE,
	// 질문글 검색
	SEARCH_QUESTIONS_REQUEST,
	SEARCH_QUESTIONS_SUCCESS,
	SEARCH_QUESTIONS_FAILURE,
	// 메뉴에서 항목 선택
	SELECT_MENU_REQUEST,
	// search navigation 항목 선택
	SELECT_NAVIGATION_REQUEST,
};
